# Schema for the configuration files of the lightbox2 module.

lightbox2.settings:
  type: config_object
  label: 'External Links Settings'
  mapping:
    enable_login:
      type: boolean
      label: 'Enable login support so that the login form appears in a lightbox.'